version: "3.8"
services:

    redis:
        image: redis:alpine
        container_name: redis

    postgres:
        image: postgres:11.0-alpine
        container_name: postgres
        volumes:
            - "./sourcefiles/postgres:/var/lib/postgresql/data"
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=12345
            - POSTGRES_DB=larka
        ports:
            - "5432:5432"

    webserver:
        image: nginx:alpine
        container_name: webserver
        working_dir: /var/www
        restart: unless-stopped
        tty: true
        volumes:
            - ./:/var/www
            - ./sourcefiles/nginx:/etc/nginx/conf.d
        ports:
            - "80:80"

    php-fpm:
        build: sourcefiles/php-fpm
        container_name: php-fpm
        working_dir: /var/www
        volumes:
            - ./:/var/www
            - ./sourcefiles/php-fpm/php-ini-overrides.ini:/etc/php/7.3/fpm/conf.d/99-overrides.ini

